// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smsatiiiukghhbrsaqug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtc2F0aWlpdWtnaGhicnNhcXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzg1OTYsImV4cCI6MjA2MDc1NDU5Nn0.9nzMQPhrFkyKpmWNejEzMjAVZOALvmyp2i9JoCK6Ge8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);